/**
 * Schema types for UI components
 * In standalone package, these types are provided via schemas.d.ts
 * In main app, these are imported from @/schemas
 */

// Re-export from main schemas if available, otherwise use local types
export type {
  Scene,
  Solution,
  KeyPoint,
  Project,
  BlogArticle,
} from '@/schemas'

// GeneratedDemo type (from demoGenerator)
export interface GeneratedDemo {
  id: string
  code: string
  autoGenerated: boolean
  generator: string
  createdAt: string
  template: string
  version: number
  metadata?: {
    techStack: string[]
    dependencies?: Record<string, string>
  }
}
