/**
 * SolutionPanel - 解决方案面板组件
 * 领域组件，只依赖 schema 类型
 */

import React from 'react'
import {
  Box,
  Typography,
  Paper,
  Stack,
  Alert,
} from '@mui/material'
import { CodeBlock } from '../blocks/CodeBlock'
import { Badge } from '../primitives/Badge'
import type { Solution } from '../schemas'

export interface SolutionPanelProps {
  /**
   * 解决方案数据（必须符合 Solution Schema）
   */
  solution: Solution
  /**
   * 是否显示代码示例
   * @default true
   */
  showCodeExample?: boolean
  /**
   * 是否显示技术要点
   * @default true
   */
  showKeyPoints?: boolean
  /**
   * 自定义样式
   */
  sx?: React.CSSProperties
}

/**
 * 解决方案面板组件
 * 
 * @example
 * ```tsx
 * <SolutionPanel
 *   solution={solution}
 *   showCodeExample={true}
 *   showKeyPoints={true}
 * />
 * ```
 */
export const SolutionPanel: React.FC<SolutionPanelProps> = ({
  solution,
  showCodeExample = true,
  showKeyPoints = true,
  sx,
}) => {
  return (
    <Paper sx={{ p: 3, ...sx }}>
      {solution.autoGenerated && (
        <Alert severity="info" sx={{ mb: 2 }}>
          This solution was auto-generated by {solution.generator || 'unknown'}
        </Alert>
      )}

      {/* Problem */}
      <Box sx={{ mb: 3 }}>
        <Typography variant="subtitle1" fontWeight={600} gutterBottom>
          Problem
        </Typography>
        <Typography variant="body1" color="text.secondary" sx={{ whiteSpace: 'pre-wrap' }}>
          {solution.problem}
        </Typography>
      </Box>

      {/* Approach */}
      <Box sx={{ mb: 3 }}>
        <Typography variant="subtitle1" fontWeight={600} gutterBottom>
          Approach
        </Typography>
        <Typography variant="body1" color="text.secondary" sx={{ whiteSpace: 'pre-wrap' }}>
          {solution.approach}
        </Typography>
      </Box>

      {/* Code Example */}
      {showCodeExample && solution.codeDemo && (
        <Box sx={{ mb: 3 }}>
          <Typography variant="subtitle1" fontWeight={600} gutterBottom>
            Code Example
          </Typography>
          <CodeBlock code={solution.codeDemo} language="tsx" />
        </Box>
      )}

      {/* Key Points */}
      {showKeyPoints && solution.keyPoints.length > 0 && (
        <Box>
          <Typography variant="subtitle1" fontWeight={600} gutterBottom>
            Key Points
          </Typography>
          <Stack spacing={2}>
            {solution.keyPoints.map((kp) => (
              <Box key={kp.id} sx={{ pl: 2, borderLeft: 2, borderColor: 'primary.main' }}>
                <Typography variant="body1" fontWeight={600}>
                  {kp.title}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  {kp.description}
                </Typography>
                {kp.tags.length > 0 && (
                  <Stack direction="row" spacing={0.5} sx={{ mt: 1 }} flexWrap="wrap">
                    {kp.tags.map((tag) => (
                      <Badge key={tag} label={tag} size="small" variant="outlined" />
                    ))}
                  </Stack>
                )}
                {kp.tradeOffs && (
                  <Box sx={{ mt: 1 }}>
                    <Typography variant="caption" color="text.secondary">
                      Trade-offs: {Object.entries(kp.tradeOffs)
                        .filter(([_, v]) => v)
                        .map(([k, v]) => `${k}: ${v}`)
                        .join(', ')}
                    </Typography>
                  </Box>
                )}
              </Box>
            ))}
          </Stack>
        </Box>
      )}
    </Paper>
  )
}
