/**
 * Type definitions for schemas
 * These types should be provided by @tech-portfolio/schemas package
 * or defined in your project
 */

export interface KeyPoint {
  id: string
  title: string
  description: string
  tags: string[]
  codeExample?: string
  tradeOffs?: {
    performance?: string
    complexity?: string
    maintainability?: string
  }
}

export interface Solution {
  id: string
  problem: string
  approach: string
  codeDemo?: string
  keyPoints: KeyPoint[]
  autoGenerated?: boolean
  generator?: 'cursor' | 'gpt-4' | 'manual' | 'template'
  createdAt?: string
  updatedAt?: string
}

export interface Scene {
  id: string
  title: string
  context: string
  category: string
  tags: string[]
  solutions: Solution[]
  createdAt?: string
  updatedAt?: string
}

export interface GeneratedDemo {
  id: string
  code: string
  autoGenerated: boolean
  generator: string
  createdAt: string
  template: string
  version: number
  metadata?: {
    techStack: string[]
    dependencies?: Record<string, string>
  }
}
