import React, { useState, useMemo } from 'react'
import {
  Box,
  Typography,
  Drawer,
  IconButton,
  useMediaQuery,
  useTheme,
} from '@mui/material'
import { Menu, Close } from '@mui/icons-material'
import { Sidebar } from '@/components/Sidebar'
import { SceneCard } from '@/components/SceneCard'
import { SceneViewer } from '@/components/SceneViewer'
import { MarkdownImporter } from '@/components/MarkdownImporter'
import { MarkdownExporter } from '@/components/MarkdownExporter'
import { scenes, categories, allTags } from '@/data/scenes'
import type { Scene } from '@/schemas'
import { parseScene } from '@/utils/validation'
import { useLanguage } from '@/hooks/useLanguage'

export const Knowledge: React.FC = () => {
  const theme = useTheme()
  const isMobile = useMediaQuery(theme.breakpoints.down('md'))
  const { t } = useLanguage()
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null)
  const [selectedTag, setSelectedTag] = useState<string | null>(null)
  const [selectedScene, setSelectedScene] = useState<Scene | null>(null)
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [detailOpen, setDetailOpen] = useState(false)
  const [allScenes, setAllScenes] = useState<Scene[]>(scenes)

  // Filter scenes based on selected category and tag
  const filteredScenes = useMemo(() => {
    return allScenes.filter((scene) => {
      const matchesCategory = !selectedCategory || scene.category === selectedCategory
      const matchesTag = !selectedTag || scene.tags.includes(selectedTag)
      return matchesCategory && matchesTag
    })
  }, [selectedCategory, selectedTag, allScenes])

  // Auto-select first scene when filter changes or no scene is selected
  React.useEffect(() => {
    if (filteredScenes.length > 0) {
      const isCurrentSceneInFiltered = selectedScene && filteredScenes.some(s => s.id === selectedScene.id)
      if (!isCurrentSceneInFiltered) {
        setSelectedScene(filteredScenes[0])
      }
    } else {
      setSelectedScene(null)
    }
  }, [filteredScenes])

  const handleCategorySelect = (category: string | null) => {
    setSelectedCategory(category)
    if (isMobile) {
      setSidebarOpen(false)
    }
  }

  const handleTagSelect = (tag: string | null) => {
    setSelectedTag(tag)
    if (isMobile) {
      setSidebarOpen(false)
    }
  }

  const handleSceneClick = (scene: Scene) => {
    setSelectedScene(scene)
    if (isMobile) {
      setDetailOpen(true)
    }
  }

  const handleMarkdownImport = (importedScene: Scene) => {
    try {
      // 验证导入的场景
      const validatedScene = parseScene(importedScene)
      // 添加到场景列表
      setAllScenes((prev) => [...prev, validatedScene])
      // 自动选中新导入的场景
      setSelectedScene(validatedScene)
      if (isMobile) {
        setDetailOpen(true)
      }
    } catch (error) {
      console.error('Failed to import scene:', error)
    }
  }

  const handleGenerateDemo = (solution: Scene['solutions'][number], demoCode: string) => {
    // 更新场景中的解决方案代码
    if (selectedScene) {
      const updatedScene: Scene = {
        ...selectedScene,
        solutions: selectedScene.solutions.map((sol) =>
          sol.id === solution.id
            ? { ...sol, codeDemo: demoCode, autoGenerated: true, generator: 'manual' }
            : sol
        ),
      }
      setSelectedScene(updatedScene)
      // 更新场景列表
      setAllScenes((prev) =>
        prev.map((s) => (s.id === updatedScene.id ? updatedScene : s))
      )
    }
  }

  return (
    <Box sx={{ display: 'flex', minHeight: 'calc(100vh - 64px)' }}>
      {/* Desktop Sidebar */}
      {!isMobile && (
        <Sidebar
          categories={categories}
          tags={allTags}
          selectedCategory={selectedCategory}
          selectedTag={selectedTag}
          onCategorySelect={handleCategorySelect}
          onTagSelect={handleTagSelect}
        />
      )}

      {/* Mobile Sidebar Drawer */}
      {isMobile && (
        <Drawer
          anchor="left"
          open={sidebarOpen}
          onClose={() => setSidebarOpen(false)}
          ModalProps={{
            keepMounted: true,
          }}
        >
          <Box sx={{ width: 280, position: 'relative' }}>
            <Box sx={{ p: 2, display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: 1, borderColor: 'divider' }}>
              <Typography variant="h6" fontWeight={600}>
                {t.knowledge.filters}
              </Typography>
              <IconButton onClick={() => setSidebarOpen(false)} size="small">
                <Close />
              </IconButton>
            </Box>
            <Sidebar
              categories={categories}
              tags={allTags}
              selectedCategory={selectedCategory}
              selectedTag={selectedTag}
              onCategorySelect={handleCategorySelect}
              onTagSelect={handleTagSelect}
            />
          </Box>
        </Drawer>
      )}

      {/* Main Content Area */}
      <Box sx={{ flex: 1, display: 'flex', flexDirection: { xs: 'column', md: 'row' }, overflow: 'hidden' }}>
        {/* Mobile Filter Button */}
        {isMobile && (
          <Box sx={{ p: 2, borderBottom: 1, borderColor: 'divider', bgcolor: 'background.paper', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <Typography variant="h6" fontWeight={600}>
              {t.knowledge.knowledgeBase}
            </Typography>
            <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
              <MarkdownImporter onImport={handleMarkdownImport} />
              <MarkdownExporter scenes={allScenes} buttonText="Export" />
              <IconButton onClick={() => setSidebarOpen(true)}>
                <Menu />
              </IconButton>
            </Box>
          </Box>
        )}

        {/* Desktop Import Button */}
        {!isMobile && (
          <Box sx={{ p: 2, borderBottom: 1, borderColor: 'divider', bgcolor: 'background.paper' }}>
            <MarkdownImporter onImport={handleMarkdownImport} />
          </Box>
        )}

        {/* Scene List */}
        <Box
          sx={{
            width: { xs: '100%', md: 400 },
            borderRight: { xs: 0, md: 1 },
            borderColor: 'divider',
            overflow: 'auto',
            bgcolor: 'background.default',
            maxHeight: { xs: '50vh', md: 'none' },
          }}
        >
          <Box sx={{ p: 2, borderBottom: 1, borderColor: 'divider', bgcolor: 'background.paper' }}>
            <Typography variant="h6" fontWeight={600}>
              {t.knowledge.scenes}
            </Typography>
            <Typography variant="body2" color="text.secondary">
              {filteredScenes.length} {filteredScenes.length === 1 ? t.knowledge.sceneFound : t.knowledge.scenesFound}
            </Typography>
          </Box>
          <Box sx={{ p: 2, display: 'flex', flexDirection: 'column', gap: 2 }}>
            {filteredScenes.length === 0 ? (
              <Typography variant="body2" color="text.secondary" sx={{ textAlign: 'center', py: 4 }}>
                {t.knowledge.noScenes}
              </Typography>
            ) : (
              filteredScenes.map((scene) => (
                <SceneCard
                  key={scene.id}
                  scene={scene}
                  onClick={() => handleSceneClick(scene)}
                  selected={selectedScene?.id === scene.id}
                />
              ))
            )}
          </Box>
        </Box>

        {/* Scene Detail - Desktop */}
        {!isMobile && (
          <Box sx={{ flex: 1, overflow: 'auto', bgcolor: 'background.paper' }}>
            <SceneViewer scene={selectedScene} onGenerateDemo={handleGenerateDemo} />
          </Box>
        )}

        {/* Scene Detail - Mobile Drawer */}
        {isMobile && (
          <Drawer
            anchor="bottom"
            open={detailOpen}
            onClose={() => setDetailOpen(false)}
            PaperProps={{
              sx: {
                height: '90vh',
                borderTopLeftRadius: 16,
                borderTopRightRadius: 16,
              },
            }}
          >
            <Box sx={{ position: 'sticky', top: 0, bgcolor: 'background.paper', zIndex: 1, p: 2, borderBottom: 1, borderColor: 'divider' }}>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Typography variant="h6" fontWeight={600}>
                  {t.knowledge.sceneDetails}
                </Typography>
                <IconButton onClick={() => setDetailOpen(false)} size="small">
                  <Close />
                </IconButton>
              </Box>
            </Box>
            <Box sx={{ overflow: 'auto', height: '100%' }}>
              <SceneViewer scene={selectedScene} onGenerateDemo={handleGenerateDemo} />
            </Box>
          </Drawer>
        )}
      </Box>
    </Box>
  )
}
