/**
 * 核心领域模型 Schema
 * 使用 Zod 定义所有数据模型，确保类型安全和运行时校验
 */

import { z } from 'zod'

// ==================== 基础模型 ====================

/**
 * 技术要点 Schema
 */
export const KeyPointSchema = z.object({
  id: z.string(),
  title: z.string().min(1, '技术要点标题不能为空'),
  description: z.string().min(1, '技术要点描述不能为空'),
  tags: z.array(z.string()).default([]),
  codeExample: z.string().optional(),
  tradeOffs: z.object({
    performance: z.string().optional(),
    complexity: z.string().optional(),
    maintainability: z.string().optional(),
  }).optional(),
})

export type KeyPoint = z.infer<typeof KeyPointSchema>

/**
 * 解决方案 Schema
 */
export const SolutionSchema = z.object({
  id: z.string(),
  problem: z.string().min(1, '问题描述不能为空'),
  approach: z.string().min(1, '解决思路不能为空'),
  codeDemo: z.string().optional(),
  keyPoints: z.array(KeyPointSchema).min(1, '至少需要一个技术要点'),
  autoGenerated: z.boolean().default(false),
  generator: z.enum(['cursor', 'gpt-4', 'manual']).optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export type Solution = z.infer<typeof SolutionSchema>

/**
 * 场景 Schema
 */
export const SceneSchema = z.object({
  id: z.string(),
  title: z.string().min(1, '场景标题不能为空'),
  context: z.string().min(1, '场景背景不能为空'),
  category: z.string().min(1, '分类不能为空'),
  tags: z.array(z.string()).default([]),
  solutions: z.array(SolutionSchema).min(1, '至少需要一个解决方案'),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export type Scene = z.infer<typeof SceneSchema>

// ==================== 项目模型 ====================

/**
 * 项目 Schema
 */
export const ProjectSchema = z.object({
  id: z.string(),
  title: z.string().min(1, '项目标题不能为空'),
  description: z.string().min(1, '项目描述不能为空'),
  techStack: z.array(z.string()).min(1, '至少需要一个技术栈'),
  type: z.enum(['Tool', 'Experiment', 'FullStack']),
  status: z.enum(['completed', 'in-progress', 'archived']).optional(),
  keyPoints: z.array(z.string()).optional(),
  codeExample: z.string().optional(),
  demoUrl: z.string().url().optional().or(z.literal('')),
  githubUrl: z.string().url().optional().or(z.literal('')),
  liveUrl: z.string().url().optional().or(z.literal('')),
  highlights: z.array(z.string()).optional(),
  autoGenerated: z.boolean().default(false),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export type Project = z.infer<typeof ProjectSchema>

// ==================== 博客模型 ====================

/**
 * 博客文章 Schema
 */
export const BlogArticleSchema = z.object({
  id: z.string(),
  title: z.string().min(1, '文章标题不能为空'),
  summary: z.string().min(1, '文章摘要不能为空'),
  content: z.string().min(1, '文章内容不能为空'),
  tags: z.array(z.string()).default([]),
  category: z.string().optional(),
  author: z.string().default('Norah Wu'),
  date: z.string(),
  readingTime: z.number().int().positive(),
  keyPoints: z.array(z.string()).optional(),
  relatedArticles: z.array(z.string()).optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export type BlogArticle = z.infer<typeof BlogArticleSchema>

// ==================== 导出所有 Schema ====================

export const Schemas = {
  KeyPoint: KeyPointSchema,
  Solution: SolutionSchema,
  Scene: SceneSchema,
  Project: ProjectSchema,
  BlogArticle: BlogArticleSchema,
} as const
