/**
 * 核心领域模型 Schema
 * 使用 Zod 定义所有数据模型，确保类型安全和运行时校验
 */

import { z } from 'zod'

// ==================== 基础模型 ====================

/**
 * 技术要点 Schema
 */
export const KeyPointSchema = z.object({
  id: z.string(),
  title: z.string().min(1, 'Key point title cannot be empty'),
  description: z.string().min(1, 'Key point description cannot be empty'),
  tags: z.array(z.string()).default([]),
  codeExample: z.string().optional(),
  tradeOffs: z.object({
    performance: z.string().optional(),
    complexity: z.string().optional(),
    maintainability: z.string().optional(),
  }).optional(),
})

export type KeyPoint = z.infer<typeof KeyPointSchema>

/**
 * 解决方案 Schema
 */
export const SolutionSchema = z.object({
  id: z.string(),
  problem: z.string().min(1, 'Problem description cannot be empty'),
  approach: z.string().min(1, 'Approach description cannot be empty'),
  codeDemo: z.string().optional(),
  keyPoints: z.array(KeyPointSchema).min(1, 'At least one key point is required'),
  autoGenerated: z.boolean().default(false),
  generator: z.enum(['cursor', 'gpt-4', 'manual']).optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export type Solution = z.infer<typeof SolutionSchema>

/**
 * 场景 Schema
 */
export const SceneSchema = z.object({
  id: z.string(),
  title: z.string().min(1, 'Scene title cannot be empty'),
  context: z.string().min(1, 'Scene context cannot be empty'),
  category: z.string().min(1, 'Category cannot be empty'),
  tags: z.array(z.string()).default([]),
  solutions: z.array(SolutionSchema).min(1, 'At least one solution is required'),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export type Scene = z.infer<typeof SceneSchema>

// ==================== 项目模型 ====================

/**
 * 项目 Schema
 */
export const ProjectSchema = z.object({
  id: z.string(),
  title: z.string().min(1, 'Project title cannot be empty'),
  description: z.string().min(1, 'Project description cannot be empty'),
  techStack: z.array(z.string()).min(1, 'At least one tech stack is required'),
  type: z.enum(['Tool', 'Experiment', 'FullStack']),
  status: z.enum(['completed', 'in-progress', 'archived']).optional(),
  keyPoints: z.array(z.string()).optional(),
  codeExample: z.string().optional(),
  demoUrl: z.union([z.string().url(), z.literal('')]).optional(),
  githubUrl: z.union([z.string().url(), z.literal('')]).optional(),
  liveUrl: z.union([z.string().url(), z.literal('')]).optional(),
  highlights: z.array(z.string()).optional(),
  autoGenerated: z.boolean().default(false),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export type Project = z.infer<typeof ProjectSchema>

// ==================== 博客模型 ====================

/**
 * 博客文章 Schema
 */
export const BlogArticleSchema = z.object({
  id: z.string(),
  title: z.string().min(1, 'Article title cannot be empty'),
  summary: z.string().min(1, 'Article summary cannot be empty'),
  content: z.string().min(1, 'Article content cannot be empty'),
  tags: z.array(z.string()).default([]),
  category: z.string().optional(),
  author: z.string().default('Norah Wu'),
  date: z.string(),
  readingTime: z.number().int().positive(),
  keyPoints: z.array(z.string()).optional(),
  relatedArticles: z.array(z.string()).optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
})

export type BlogArticle = z.infer<typeof BlogArticleSchema>

// ==================== 导出所有 Schema ====================

export const Schemas = {
  KeyPoint: KeyPointSchema,
  Solution: SolutionSchema,
  Scene: SceneSchema,
  Project: ProjectSchema,
  BlogArticle: BlogArticleSchema,
} as const
