/**
 * DemoPreview - Demo 代码预览和执行组件
 * 支持 Sandpack 和 iframe 两种预览方式
 */

import React, { useState } from 'react'
import {
  Box,
  Paper,
  Tabs,
  Tab,
  Typography,
  IconButton,
  Tooltip,
  Alert,
  CircularProgress,
} from '@mui/material'
import { Code, PlayArrow, ContentCopy, Check, Refresh } from '@mui/icons-material'
import { CodeBlock } from './CodeBlock'
import { type GeneratedDemo } from '@/utils/demoGenerator'
import { generateCodeSandboxConfig } from '@/utils/demoGenerator'

interface DemoPreviewProps {
  demo: GeneratedDemo
  onRegenerate?: () => void
  showCode?: boolean
}

/**
 * Demo 预览组件
 * 支持代码查看和在线预览
 */
export const DemoPreview: React.FC<DemoPreviewProps> = ({
  demo,
  onRegenerate,
  showCode = true,
}) => {
  const [activeTab, setActiveTab] = useState<'code' | 'preview'>('code')
  const [copied, setCopied] = useState(false)
  const [loading, setLoading] = useState(false)

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(demo.code)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (error) {
      console.error('Failed to copy code:', error)
    }
  }

  const handleOpenCodeSandbox = () => {
    const config = generateCodeSandboxConfig(demo)
    const form = document.createElement('form')
    form.method = 'POST'
    form.action = 'https://codesandbox.io/api/v1/sandboxes/define?json=1'
    form.target = '_blank'

    const input = document.createElement('input')
    input.type = 'hidden'
    input.name = 'parameters'
    input.value = JSON.stringify(config)
    form.appendChild(input)

    document.body.appendChild(form)
    form.submit()
    document.body.removeChild(form)
  }

  return (
    <Paper sx={{ p: 2, mb: 2 }}>
      {/* Header */}
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
        <Box>
          <Typography variant="h6" fontWeight={600}>
            Generated Demo
          </Typography>
          <Typography variant="caption" color="text.secondary">
            Generated by {demo.generator} • Version {demo.version} • {new Date(demo.createdAt).toLocaleString()}
          </Typography>
        </Box>
        <Box sx={{ display: 'flex', gap: 1 }}>
          <Tooltip title="Copy Code">
            <IconButton size="small" onClick={handleCopy}>
              {copied ? <Check color="success" /> : <ContentCopy />}
            </IconButton>
          </Tooltip>
          <Tooltip title="Open in CodeSandbox">
            <IconButton size="small" onClick={handleOpenCodeSandbox}>
              <PlayArrow />
            </IconButton>
          </Tooltip>
          {onRegenerate && (
            <Tooltip title="Regenerate">
              <IconButton size="small" onClick={onRegenerate}>
                <Refresh />
              </IconButton>
            </Tooltip>
          )}
        </Box>
      </Box>

      {/* Auto-generated Badge */}
      {demo.autoGenerated && (
        <Alert severity="info" sx={{ mb: 2 }}>
          This demo was auto-generated by {demo.generator}. You can regenerate or edit it manually.
        </Alert>
      )}

      {/* Tabs */}
      {showCode && (
        <Tabs value={activeTab} onChange={(_, newValue) => setActiveTab(newValue)} sx={{ mb: 2 }}>
          <Tab label="Code" value="code" icon={<Code />} iconPosition="start" />
          <Tab label="Preview" value="preview" icon={<PlayArrow />} iconPosition="start" />
        </Tabs>
      )}

      {/* Content */}
      {showCode && activeTab === 'code' ? (
        <Box>
          <CodeBlock code={demo.code} language="tsx" />
        </Box>
      ) : (
        <Box sx={{ minHeight: 400, position: 'relative' }}>
          {loading && (
            <Box
              sx={{
                position: 'absolute',
                top: '50%',
                left: '50%',
                transform: 'translate(-50%, -50%)',
              }}
            >
              <CircularProgress />
            </Box>
          )}
          <iframe
            src={`https://codesandbox.io/embed/new?template=create-react-app-typescript`}
            style={{
              width: '100%',
              height: '400px',
              border: 0,
              borderRadius: '4px',
              overflow: 'hidden',
            }}
            title="Demo Preview"
            allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
            sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
            onLoad={() => setLoading(false)}
          />
          <Box sx={{ mt: 2, textAlign: 'center' }}>
            <Typography variant="body2" color="text.secondary">
              Click "Open in CodeSandbox" above to view the full interactive demo
            </Typography>
          </Box>
        </Box>
      )}
    </Paper>
  )
}
