import React, { useState } from 'react'
import {
  Box,
  Typography,
  List,
  ListItem,
  ListItemText,
  Divider,
  Collapse,
  IconButton,
  Button,
  Stack,
  Paper,
} from '@mui/material'
import { ExpandLess, ExpandMore, Launch, GitHub } from '@mui/icons-material'
import { CodeBlock } from './CodeBlock'
import { LiveDemo } from './LiveDemo'
import { Tag } from './Tag'
import type { Project } from '@/data/projectsData'

interface ProjectDetailProps {
  project: Project | null
}

export const ProjectDetail: React.FC<ProjectDetailProps> = ({ project }) => {
  const [keyPointsExpanded, setKeyPointsExpanded] = useState(true)

  if (!project) {
    return (
      <Box
        sx={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          height: '100%',
          color: 'text.secondary',
        }}
      >
        <Typography variant="h6">Select a project to view details</Typography>
      </Box>
    )
  }

  const handleToggleKeyPoints = () => {
    setKeyPointsExpanded(!keyPointsExpanded)
  }

  return (
    <Box sx={{ p: 3, height: '100%', overflow: 'auto' }}>
      <Box sx={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', mb: 2 }}>
        <Box sx={{ flex: 1 }}>
          <Typography variant="h4" component="h1" fontWeight={700} gutterBottom>
            {project.title}
          </Typography>
          {project.autoGenerated && (
            <Tag label="Auto Generated" color="secondary" size="small" sx={{ mt: 1 }} />
          )}
        </Box>
        <Stack direction="row" spacing={1}>
          {project.githubUrl && (
            <Button
              component="a"
              href={project.githubUrl}
              target="_blank"
              rel="noopener noreferrer"
              startIcon={<GitHub />}
              variant="outlined"
              size="small"
            >
              GitHub
            </Button>
          )}
          {project.liveUrl && (
            <Button
              component="a"
              href={project.liveUrl}
              target="_blank"
              rel="noopener noreferrer"
              startIcon={<Launch />}
              variant="contained"
              size="small"
            >
              Live Demo
            </Button>
          )}
        </Stack>
      </Box>

      <Typography variant="body1" color="text.secondary" paragraph>
        {project.description}
      </Typography>

      <Box sx={{ display: 'flex', gap: 1, mb: 3, flexWrap: 'wrap' }}>
        <Tag label={project.type} color="primary" />
        {project.status && (
          <Tag label={project.status.replace('-', ' ')} color="default" />
        )}
        {project.techStack.map((tech) => (
          <Tag key={tech} label={tech} />
        ))}
      </Box>

      <Divider sx={{ my: 3 }} />

      {project.solution && (
        <>
          <Typography variant="h6" component="h2" gutterBottom fontWeight={600}>
            Solution
          </Typography>
          <Paper elevation={0} sx={{ p: 3, mb: 4, bgcolor: 'grey.50' }}>
            <Typography
              variant="body1"
              component="div"
              sx={{
                whiteSpace: 'pre-line',
                lineHeight: 1.8,
              }}
            >
              {project.solution}
            </Typography>
          </Paper>
        </>
      )}

      {project.highlights && project.highlights.length > 0 && (
        <>
          <Typography variant="h6" component="h2" gutterBottom fontWeight={600}>
            Highlights
          </Typography>
          <Box sx={{ mb: 4 }}>
            <List>
              {project.highlights.map((highlight, index) => (
                <ListItem key={index}>
                  <ListItemText
                    primary={
                      <Typography variant="body1">
                        • {highlight}
                      </Typography>
                    }
                  />
                </ListItem>
              ))}
            </List>
          </Box>
        </>
      )}

      {project.codeExample && (
        <>
          <Typography variant="h6" component="h2" gutterBottom fontWeight={600}>
            Code Example
          </Typography>
          <Box sx={{ mb: 4 }}>
            <CodeBlock
              code={project.codeExample.code}
              language={project.codeExample.language}
            />
          </Box>
        </>
      )}

      {project.demoUrl && (
        <>
          <Typography variant="h6" component="h2" gutterBottom fontWeight={600}>
            Live Demo
          </Typography>
          <Box sx={{ mb: 4 }}>
            <LiveDemo
              demoUrl={project.demoUrl}
              title={project.title}
              description={project.description}
            />
          </Box>
        </>
      )}

      <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 1 }}>
        <Typography variant="h6" component="h2" fontWeight={600}>
          Key Points
        </Typography>
        <IconButton onClick={handleToggleKeyPoints} size="small" aria-label="toggle key points">
          {keyPointsExpanded ? <ExpandLess /> : <ExpandMore />}
        </IconButton>
      </Box>
      <Collapse in={keyPointsExpanded} timeout="auto" unmountOnExit>
        <List>
          {project.keyPoints.map((point, index) => (
            <React.Fragment key={index}>
              <ListItem alignItems="flex-start">
                <ListItemText
                  primary={
                    <Typography variant="subtitle1" fontWeight={600}>
                      {point}
                    </Typography>
                  }
                />
              </ListItem>
              {index < project.keyPoints.length - 1 && <Divider component="li" />}
            </React.Fragment>
          ))}
        </List>
      </Collapse>
    </Box>
  )
}
