import React, { useState } from 'react'
import {
  Card,
  CardContent,
  CardHeader,
  Typography,
  Box,
  Stack,
  Tooltip,
} from '@mui/material'
import { ArrowForward, Code, Launch } from '@mui/icons-material'
import { Tag } from './Tag'
import type { Project } from '@/schemas'
import { useLanguage } from '@/hooks/useLanguage'

interface ProjectCardProps {
  project: Project
  onClick: () => void
  selected?: boolean
}

// Type labels will be handled by i18n

const statusColors: Record<string, 'default' | 'primary' | 'secondary' | 'success' | 'warning'> = {
  completed: 'success',
  'in-progress': 'warning',
  archived: 'default',
}

export const ProjectCard: React.FC<ProjectCardProps> = ({
  project,
  onClick,
  selected = false,
}) => {
  const { t } = useLanguage()
  const [showDescription, setShowDescription] = useState(false)
  
  const getTypeLabel = (type: string): string => {
    switch (type) {
      case 'Tool':
        return t.projects.tool
      case 'Experiment':
        return t.projects.experiment
      case 'FullStack':
        return t.projects.fullStack
      default:
        return type
    }
  }

  return (
    <Tooltip
      title={project.description}
      arrow
      placement="top"
      open={showDescription}
      onOpen={() => setShowDescription(true)}
      onClose={() => setShowDescription(false)}
    >
      <Card
        onClick={onClick}
        onMouseEnter={() => setShowDescription(true)}
        onMouseLeave={() => setShowDescription(false)}
        sx={{
          cursor: 'pointer',
          transition: 'all 0.2s',
          border: selected ? 2 : 1,
          borderColor: selected ? 'primary.main' : 'divider',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          '&:hover': {
            transform: 'translateY(-4px)',
            boxShadow: 4,
            borderColor: 'primary.main',
            bgcolor: 'action.hover',
          },
        }}
      >
        <CardHeader
          title={
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap' }}>
              <Typography variant="h6" component="h3" fontWeight={600}>
                {project.title}
              </Typography>
              <Tag
                label={getTypeLabel(project.type)}
                color="primary"
                variant="outlined"
              />
              {project.status && (
                <Tag
                  label={project.status.replace('-', ' ')}
                  color={statusColors[project.status]}
                  variant="filled"
                />
              )}
              {project.autoGenerated && (
                <Tag
                  label={t.projects.auto}
                  color="secondary"
                  size="small"
                />
              )}
            </Box>
          }
        />
        <CardContent sx={{ flexGrow: 1, display: 'flex', flexDirection: 'column' }}>
          <Typography
            variant="body2"
            color="text.secondary"
            paragraph
            sx={{
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              display: '-webkit-box',
              WebkitLineClamp: 2,
              WebkitBoxOrient: 'vertical',
              minHeight: 40,
            }}
          >
            {project.description}
          </Typography>

          <Box sx={{ mb: 2 }}>
            <Typography variant="caption" color="text.secondary" sx={{ mb: 0.5, display: 'block' }}>
              {t.projects.techStackLabel}:
            </Typography>
            <Stack direction="row" spacing={0.5} flexWrap="wrap" useFlexGap>
              {project.techStack.slice(0, 4).map((tech) => (
                <Tag key={tech} label={tech} />
              ))}
              {project.techStack.length > 4 && (
                <Tag label={`+${project.techStack.length - 4}`} />
              )}
            </Stack>
          </Box>

          {project.highlights && project.highlights.length > 0 && (
            <Box sx={{ mb: 2 }}>
              <Typography variant="caption" color="text.secondary" sx={{ mb: 0.5, display: 'block' }}>
                {t.projects.highlightsLabel}:
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ fontSize: '0.75rem' }}>
                {project.highlights.slice(0, 2).join(' • ')}
                {project.highlights.length > 2 && ' • ...'}
              </Typography>
            </Box>
          )}

          <Box sx={{ mt: 'auto', display: 'flex', gap: 1, alignItems: 'center', pt: 2 }}>
            <Box sx={{ display: 'flex', alignItems: 'center', color: 'primary.main', flex: 1 }}>
              <Typography variant="body2" sx={{ fontWeight: 500 }}>
                {t.projects.viewDetails}
              </Typography>
              <ArrowForward sx={{ ml: 1, fontSize: 16 }} />
            </Box>
            {project.githubUrl && (
              <Code sx={{ fontSize: 18, color: 'text.secondary' }} />
            )}
            {project.liveUrl && (
              <Launch sx={{ fontSize: 18, color: 'text.secondary' }} />
            )}
          </Box>
        </CardContent>
      </Card>
    </Tooltip>
  )
}
