/**
 * 数据适配器
 * 将旧格式数据转换为新的 Schema 格式
 */

import { parseScene, parseProject, parseBlogArticle } from './validation'
import type { Scene, Solution, Project, BlogArticle } from '@/schemas'
import type { KnowledgeScene } from '@/data/knowledgeData'
import type { Project as OldProject } from '@/data/projectsData'
import type { BlogArticle as OldBlogArticle } from '@/data/blogData'

/**
 * 将旧的 KnowledgeScene 转换为新的 Scene 格式
 */
export function adaptKnowledgeSceneToScene(oldScene: KnowledgeScene): Scene {
  // 将 description 作为 context
  const context = oldScene.description

  // 将 solution 字符串转换为 Solution 对象
  const solution: Solution = {
    id: `${oldScene.id}-solution-1`,
    problem: extractProblemFromSolution(oldScene.solution),
    approach: oldScene.solution,
    codeDemo: oldScene.codeExample ? oldScene.codeExample.code : undefined,
    keyPoints: oldScene.keyPoints.map((kp, index) => ({
      id: `${oldScene.id}-kp-${index + 1}`,
      title: kp.title,
      description: kp.description,
      tags: [],
    })),
    autoGenerated: false,
  }

  const scene: Scene = {
    id: oldScene.id,
    title: oldScene.title,
    context,
    category: oldScene.category,
    tags: oldScene.tags,
    solutions: [solution],
    createdAt: new Date().toISOString(),
  }

  // 验证并返回
  return parseScene(scene)
}

/**
 * 从 solution 字符串中提取问题描述
 */
function extractProblemFromSolution(solution: string): string {
  // 尝试从 solution 中提取问题描述
  // 如果 solution 以问题开头，提取第一段
  const lines = solution.split('\n').filter(line => line.trim())
  if (lines.length > 0) {
    const firstLine = lines[0]
    // 如果第一行包含问号或"问题"关键词，作为问题描述
    if (firstLine.includes('?') || firstLine.includes('问题') || firstLine.includes('problem')) {
      return firstLine
    }
  }
  // 默认返回一个通用问题描述
  return 'How to solve this problem?'
}

/**
 * 批量转换 KnowledgeScene 数组
 */
export function adaptKnowledgeScenesToScenes(oldScenes: KnowledgeScene[]): Scene[] {
  return oldScenes.map(adaptKnowledgeSceneToScene)
}

/**
 * 将旧的 Project 转换为新的 Project 格式
 */
export function adaptProjectToNewFormat(oldProject: OldProject): Project {
  // 处理 URL 字段：空字符串或相对路径转换为 undefined，确保符合 Schema
  const normalizeUrl = (url?: string): string | undefined => {
    if (!url || url.trim() === '') return undefined
    // 如果是相对路径（不以 http:// 或 https:// 开头），转换为 undefined
    if (!url.startsWith('http://') && !url.startsWith('https://')) {
      return undefined
    }
    return url
  }

  const project: Project = {
    id: oldProject.id,
    title: oldProject.title,
    description: oldProject.description,
    techStack: oldProject.techStack,
    type: oldProject.type,
    status: oldProject.status,
    keyPoints: oldProject.keyPoints || [],
    codeExample: oldProject.codeExample ? oldProject.codeExample.code : undefined,
    demoUrl: normalizeUrl(oldProject.demoUrl),
    githubUrl: normalizeUrl(oldProject.githubUrl),
    liveUrl: normalizeUrl(oldProject.liveUrl),
    highlights: oldProject.highlights,
    autoGenerated: oldProject.autoGenerated || false,
    createdAt: oldProject.createdAt || new Date().toISOString(),
  }

  return parseProject(project)
}

/**
 * 批量转换 Project 数组
 */
export function adaptProjectsToNewFormat(oldProjects: OldProject[]): Project[] {
  return oldProjects.map(adaptProjectToNewFormat)
}

/**
 * 将旧的 BlogArticle 转换为新的 BlogArticle 格式
 */
export function adaptBlogArticleToNewFormat(oldArticle: OldBlogArticle): BlogArticle {
  const article: BlogArticle = {
    id: oldArticle.id,
    title: oldArticle.title,
    summary: oldArticle.summary,
    content: oldArticle.content,
    tags: oldArticle.tags,
    category: oldArticle.category,
    author: oldArticle.author,
    date: oldArticle.date,
    readingTime: oldArticle.readingTime,
    keyPoints: oldArticle.keyPoints,
    relatedArticles: oldArticle.relatedArticles,
  }

  return parseBlogArticle(article)
}

/**
 * 批量转换 BlogArticle 数组
 */
export function adaptBlogArticlesToNewFormat(oldArticles: OldBlogArticle[]): BlogArticle[] {
  return oldArticles.map(adaptBlogArticleToNewFormat)
}
