/**
 * 数据校验工具
 * 在开发环境下提供额外的校验和警告
 */

import { z } from 'zod'
import type { Scene, Project, BlogArticle } from '@/schemas'
import { SceneSchema, ProjectSchema, BlogArticleSchema } from '@/schemas'

/**
 * 开发环境下的严格校验
 * 生产环境使用宽松校验以避免性能问题
 */
const isDevelopment = import.meta.env.DEV

/**
 * 校验场景数据（开发环境严格模式）
 */
export function validateSceneStrict(data: unknown): Scene {
  if (isDevelopment) {
    // 开发环境：严格校验，显示详细错误
    return SceneSchema.parse(data)
  }
  // 生产环境：使用 safeParse，失败时返回默认值
  const result = SceneSchema.safeParse(data)
  if (!result.success) {
    console.error('Scene validation failed:', result.error)
    // 返回一个最小有效的 Scene 对象
    return {
      id: 'invalid',
      title: 'Invalid Scene',
      context: 'Data validation failed',
      category: 'Error',
      tags: [],
      solutions: [],
    }
  }
  return result.data
}

/**
 * 校验项目数据
 */
export function validateProjectStrict(data: unknown): Project {
  if (isDevelopment) {
    return ProjectSchema.parse(data)
  }
  const result = ProjectSchema.safeParse(data)
  if (!result.success) {
    console.error('Project validation failed:', result.error)
    return {
      id: 'invalid',
      title: 'Invalid Project',
      description: 'Data validation failed',
      techStack: [],
      type: 'Tool',
      autoGenerated: false,
    }
  }
  return result.data
}

/**
 * 校验博客文章数据
 */
export function validateBlogArticleStrict(data: unknown): BlogArticle {
  if (isDevelopment) {
    return BlogArticleSchema.parse(data)
  }
  const result = BlogArticleSchema.safeParse(data)
  if (!result.success) {
    console.error('BlogArticle validation failed:', result.error)
    return {
      id: 'invalid',
      title: 'Invalid Article',
      summary: 'Data validation failed',
      content: '',
      tags: [],
      author: 'Unknown',
      date: new Date().toISOString(),
      readingTime: 1,
    }
  }
  return result.data
}

/**
 * 批量校验并报告
 */
export function validateBatch<T>(
  schema: z.ZodSchema<T>,
  items: unknown[],
  itemName: string
): { valid: T[]; invalidCount: number } {
  const valid: T[] = []
  let invalidCount = 0

  items.forEach((item, index) => {
    const result = schema.safeParse(item)
    if (result.success) {
      valid.push(result.data)
    } else {
      invalidCount++
      if (isDevelopment) {
        console.warn(`[Validation] Invalid ${itemName} at index ${index}:`, result.error.issues)
      }
    }
  })

  if (invalidCount > 0 && isDevelopment) {
    console.warn(`[Validation] ${invalidCount} invalid ${itemName} items filtered out`)
  }

  return { valid, invalidCount }
}
