/**
 * 代码 Demo 生成器
 * 根据 Scene context 和 Solution approach 生成可运行的 React + TS 代码
 */

import { type Scene, type Solution } from '@/schemas'

/**
 * Demo 生成选项
 */
export interface DemoGeneratorOptions {
  techStack: string[]
  generator?: 'cursor' | 'gpt-4' | 'manual' | 'template'
  template?: 'basic' | 'advanced' | 'minimal'
  includeTests?: boolean
}

/**
 * 生成的 Demo 代码结构
 */
export interface GeneratedDemo {
  id: string
  code: string
  autoGenerated: boolean
  generator: string
  createdAt: string
  template: string
  version: number
  metadata?: {
    techStack: string[]
    dependencies?: Record<string, string>
  }
}

/**
 * Demo 代码模板
 */
const DEMO_TEMPLATES = {
  basic: `import React, { useState } from 'react'

export function Demo() {
  // State
  const [state, setState] = useState(initialState)

  // Logic
  const handleAction = () => {
    // Implementation
  }

  // Render
  return (
    <div style={{ padding: '20px' }}>
      <h2>Demo</h2>
      {/* UI */}
    </div>
  )
}`,

  advanced: `import React, { useState, useEffect, useCallback } from 'react'

interface Props {
  // Props definition
}

export function Demo({ }: Props) {
  // State
  const [state, setState] = useState(initialState)

  // Effects
  useEffect(() => {
    // Side effects
    return () => {
      // Cleanup
    }
  }, [])

  // Callbacks
  const handleAction = useCallback(() => {
    // Implementation
  }, [])

  // Render
  return (
    <div style={{ padding: '20px' }}>
      <h2>Demo</h2>
      {/* UI */}
    </div>
  )
}`,

  minimal: `import React from 'react'

export function Demo() {
  return (
    <div style={{ padding: '20px' }}>
      <h2>Demo</h2>
    </div>
  )
}`,
}

/**
 * 生成 Demo 代码
 * 
 * 注意：这是一个基础实现，实际应该调用 AI API（Cursor/GPT-4）
 */
export async function generateDemo(
  scene: Scene,
  solution: Solution,
  options: DemoGeneratorOptions = { techStack: ['React', 'TypeScript'] }
): Promise<GeneratedDemo> {
  const template = options.template || 'basic'
  const generator = options.generator || 'template'
  const baseTemplate = DEMO_TEMPLATES[template]

  // 根据 solution 和 context 生成代码
  let code = baseTemplate

  // 替换占位符
  code = code.replace('// State', generateStateCode(solution, options.techStack))
  code = code.replace('// Logic', generateLogicCode(solution))
  code = code.replace('// Implementation', generateImplementation(solution))
  code = code.replace('{/* UI */}', generateUI(solution, scene))
  code = code.replace('initialState', generateInitialState(solution))
  code = code.replace('// Props definition', generateProps(solution))

  // 添加 imports（根据 techStack）
  const imports = generateImports(options.techStack)
  code = imports + '\n\n' + code

  // 格式化代码
  code = formatGeneratedCode(code)

  // 验证生成的代码
  const validation = validateGeneratedCode(code)
  if (!validation.valid) {
    console.warn('Generated code validation warnings:', validation.errors)
  }

  return {
    id: `demo-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    code,
    autoGenerated: true,
    generator,
    createdAt: new Date().toISOString(),
    template,
    version: 1,
    metadata: {
      techStack: options.techStack,
      dependencies: generateDependencies(options.techStack),
    },
  }
}

/**
 * 调用 AI API 生成 Demo（高级功能）
 */
export async function generateDemoWithAI(
  scene: Scene,
  solution: Solution,
  options: DemoGeneratorOptions & { apiKey?: string; apiUrl?: string }
): Promise<GeneratedDemo> {
  // TODO: 集成 AI API（Cursor/GPT-4）
  // 示例实现：
  /*
  const response = await fetch(options.apiUrl || '/api/generate-demo', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${options.apiKey}`,
    },
    body: JSON.stringify({
      scene: {
        title: scene.title,
        context: scene.context,
      },
      solution: {
        problem: solution.problem,
        approach: solution.approach,
        keyPoints: solution.keyPoints,
      },
      techStack: options.techStack,
      template: options.template,
    }),
  })

  const data = await response.json()
  return {
    ...data,
    autoGenerated: true,
    generator: 'gpt-4',
  }
  */

  // 暂时回退到模板生成
  return generateDemo(scene, solution, options)
}

/**
 * 生成 State 代码
 */
function generateStateCode(_solution: Solution, techStack: string[]): string {
  if (techStack.includes('Zustand')) {
    return `// Using Zustand for state management
import { create } from 'zustand'

const useStore = create((set) => ({
  value: null,
  setValue: (newValue) => set({ value: newValue }),
}))

// In component:
const { value, setValue } = useStore()`
  }
  
  if (techStack.includes('Redux')) {
    return `// Using Redux for state management
const [value, setValue] = useState(null)`
  }

  return `const [value, setValue] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)`
}

/**
 * 生成 Logic 代码
 */
function generateLogicCode(solution: Solution): string {
  const firstLine = solution.approach.split('\n')[0]
  const problemLine = solution.problem.split('\n')[0]
  return `// ${firstLine}
  const handleAction = () => {
    try {
      setLoading(true)
      // Implementation based on: ${problemLine}
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error')
    } finally {
      setLoading(false)
    }
  }`
}

/**
 * 生成实现代码
 */
function generateImplementation(solution: Solution): string {
  return `// ${solution.problem.split('\n')[0]}
    console.log('Implementing solution...')`
}

/**
 * 生成 UI 代码
 */
function generateUI(solution: Solution, scene: Scene): string {
  const firstKeyPoint = solution.keyPoints[0]
  const approachLine = solution.approach.split('\n')[0]
  return `<div>
      <h3>${scene.title}</h3>
      <p>{${approachLine}}</p>
      ${firstKeyPoint ? `{firstKeyPoint && (
        <div>
          <strong>{firstKeyPoint.title}:</strong>
          <p>{firstKeyPoint.description}</p>
        </div>
      )}` : ''}
      <button onClick={handleAction} disabled={loading}>
        {loading ? 'Loading...' : 'Execute'}
      </button>
      {error && <div style={{ color: 'red' }}>{error}</div>}
    </div>`
}

/**
 * 生成初始状态
 */
function generateInitialState(_solution: Solution): string {
  return `{
    value: null,
    loading: false,
    error: null,
  }`
}

/**
 * 生成 Props 定义
 */
function generateProps(_solution: Solution): string {
  return `// No props required`
}

/**
 * 生成 imports
 */
function generateImports(techStack: string[]): string {
  const imports: string[] = []
  
  if (techStack.includes('React')) {
    imports.push("import React, { useState } from 'react'")
  }
  
  if (techStack.includes('TypeScript')) {
    // TypeScript 类型会在代码中体现
  }
  
  if (techStack.includes('Zustand')) {
    imports.push("import { create } from 'zustand'")
  }
  
  if (techStack.includes('Redux')) {
    imports.push("import { useSelector, useDispatch } from 'react-redux'")
  }

  return imports.join('\n')
}

/**
 * 生成依赖项
 */
function generateDependencies(techStack: string[]): Record<string, string> {
  const deps: Record<string, string> = {
    react: '^18.0.0',
    'react-dom': '^18.0.0',
  }

  if (techStack.includes('Zustand')) {
    deps.zustand = '^4.0.0'
  }

  if (techStack.includes('TypeScript')) {
    deps.typescript = '^5.0.0'
    deps['@types/react'] = '^18.0.0'
    deps['@types/react-dom'] = '^18.0.0'
  }

  return deps
}

/**
 * 验证生成的代码是否符合规范
 */
export function validateGeneratedCode(code: string): { valid: boolean; errors: string[] } {
  const errors: string[] = []

  // 检查基本结构
  if (!code.includes('export function Demo')) {
    errors.push('Missing export function Demo')
  }

  if (!code.includes('return')) {
    errors.push('Missing return statement')
  }

  // 检查 React 导入
  if (!code.includes("import") && !code.includes("from 'react'")) {
    errors.push('Missing React import')
  }

  // 检查是否有语法错误（基础检查）
  if (code.includes('// TODO') || code.includes('// Implementation')) {
    errors.push('Code contains placeholder comments')
  }

  return {
    valid: errors.length === 0,
    errors,
  }
}

/**
 * 格式化生成的代码
 */
export function formatGeneratedCode(code: string): string {
  // 移除多余空行
  return code
    .split('\n')
    .map(line => line.trimEnd())
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

/**
 * 生成 CodeSandbox 配置
 */
export function generateCodeSandboxConfig(
  demo: GeneratedDemo,
  options: { template?: string } = {}
): Record<string, unknown> {
  return {
    files: {
      'package.json': {
        content: JSON.stringify({
          name: 'demo',
          version: '1.0.0',
          dependencies: demo.metadata?.dependencies || {},
        }, null, 2),
      },
      'src/Demo.tsx': {
        content: demo.code,
      },
      'src/index.tsx': {
        content: `import React from 'react'
import ReactDOM from 'react-dom/client'
import { Demo } from './Demo'

const root = ReactDOM.createRoot(document.getElementById('root')!)
root.render(<Demo />)`,
      },
      'index.html': {
        content: `<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
</head>
<body>
  <div id="root"></div>
</body>
</html>`,
      },
    },
    template: options.template || 'create-react-app-typescript',
  }
}
