export type ProjectType = 'Tool' | 'Experiment' | 'FullStack'
export type ProjectStatus = 'completed' | 'in-progress' | 'archived'

export interface Project {
  id: string
  title: string
  description: string
  techStack: string[]
  type: ProjectType
  status?: ProjectStatus
  keyPoints: string[]
  solution?: string
  codeExample?: {
    language: string
    code: string
  }
  demoUrl?: string
  githubUrl?: string
  liveUrl?: string
  createdAt: string
  autoGenerated?: boolean
  highlights?: string[]
}

export const projects: Project[] = [
  {
    id: 'p1',
    title: 'React Todo 高级实现',
    description: '使用 useReducer + Context 管理复杂状态，支持持久化和拖拽排序',
    techStack: ['React', 'TypeScript', 'Context', 'TailwindCSS'],
    type: 'Tool',
    status: 'completed',
    keyPoints: [
      'useReducer 管理复杂状态',
      '拖拽排序实现',
      '本地存储持久化',
      'TypeScript 类型安全',
    ],
    solution: `这个 Todo 应用展示了如何使用 React Hooks 和 Context API 构建复杂的状态管理方案。

主要实现：
1. 使用 useReducer 替代 useState 管理复杂状态
2. Context API 实现全局状态共享
3. localStorage 实现数据持久化
4. 拖拽排序功能使用 react-beautiful-dnd`,
    codeExample: {
      language: 'typescript',
      code: `import React, { useReducer, createContext, useContext } from 'react';

interface Todo {
  id: string;
  text: string;
  completed: boolean;
}

type TodoAction =
  | { type: 'ADD'; payload: string }
  | { type: 'TOGGLE'; payload: string }
  | { type: 'DELETE'; payload: string }
  | { type: 'REORDER'; payload: { startIndex: number; endIndex: number } };

function todoReducer(state: Todo[], action: TodoAction): Todo[] {
  switch (action.type) {
    case 'ADD':
      return [...state, { id: Date.now().toString(), text: action.payload, completed: false }];
    case 'TOGGLE':
      return state.map(todo =>
        todo.id === action.payload ? { ...todo, completed: !todo.completed } : todo
      );
    case 'DELETE':
      return state.filter(todo => todo.id !== action.payload);
    case 'REORDER':
      const result = Array.from(state);
      const [removed] = result.splice(action.payload.startIndex, 1);
      result.splice(action.payload.endIndex, 0, removed);
      return result;
    default:
      return state;
  }
}

const TodoContext = createContext<{
  todos: Todo[];
  dispatch: React.Dispatch<TodoAction>;
} | null>(null);

export function TodoProvider({ children }: { children: React.ReactNode }) {
  const [todos, dispatch] = useReducer(todoReducer, []);

  return (
    <TodoContext.Provider value={{ todos, dispatch }}>
      {children}
    </TodoContext.Provider>
  );
}

export function useTodos() {
  const context = useContext(TodoContext);
  if (!context) throw new Error('useTodos must be used within TodoProvider');
  return context;
}`
    },
    demoUrl: '/demos/todo',
    githubUrl: 'https://github.com/example/react-todo',
    createdAt: '2026-01-12',
    autoGenerated: false,
    highlights: ['useReducer', 'Context API', '拖拽排序', '持久化'],
  },
  {
    id: 'p2',
    title: '自动生成 React 小组件',
    description: '输入描述自动生成组件骨架，并展示 Live Preview',
    techStack: ['React', 'TypeScript', 'GPT API', 'Sandpack'],
    type: 'Experiment',
    status: 'in-progress',
    keyPoints: [
      '自动生成组件',
      '实时渲染 demo',
      '可多种实现方案',
      'GPT API 集成',
    ],
    solution: `这个实验性项目展示了如何使用 AI 自动生成 React 组件。

功能特点：
1. 输入自然语言描述，自动生成 React + TypeScript 组件代码
2. 支持多种实现方案（基础版、优化版、复杂版）
3. 实时预览生成的组件
4. 支持代码下载和进一步编辑`,
    codeExample: {
      language: 'typescript',
      code: `// Auto-generated component example
interface AutoGenProps {
  description: string;
  onGenerate: (code: string) => void;
}

export const AutoGenComponent: React.FC<AutoGenProps> = ({ description, onGenerate }) => {
  const [generatedCode, setGeneratedCode] = React.useState<string>('');

  const handleGenerate = async () => {
    const response = await fetch('/api/generate', {
      method: 'POST',
      body: JSON.stringify({ description }),
    });
    const { code } = await response.json();
    setGeneratedCode(code);
    onGenerate(code);
  };

  return (
    <div>
      <button onClick={handleGenerate}>Generate Component</button>
      {generatedCode && <pre>{generatedCode}</pre>}
    </div>
  );
};`
    },
    demoUrl: '/demos/auto-gen',
    createdAt: '2026-01-12',
    autoGenerated: true,
    highlights: ['AI 生成', '实时预览', '多方案支持'],
  },
  {
    id: 'p3',
    title: 'Task Manager Application',
    description: 'A full-featured task management application with drag-and-drop, real-time updates, and offline support.',
    techStack: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'WebSocket'],
    type: 'FullStack',
    status: 'completed',
    keyPoints: [
      'Real-time collaboration',
      'Offline-first architecture',
      'Advanced filtering and sorting',
      'Drag-and-drop interface',
    ],
    solution: `Full-stack task management application with real-time collaboration features.

Architecture:
- Frontend: React + TypeScript with Zustand for state management
- Backend: Node.js + Express with PostgreSQL
- Real-time: WebSocket for live updates
- Offline: IndexedDB for offline storage and sync`,
    codeExample: {
      language: 'typescript',
      code: `import { create } from 'zustand';

interface Task {
  id: string;
  title: string;
  completed: boolean;
  userId: string;
}

interface TaskStore {
  tasks: Task[];
  addTask: (task: Task) => void;
  updateTask: (id: string, updates: Partial<Task>) => void;
}

export const useTaskStore = create<TaskStore>((set) => ({
  tasks: [],
  addTask: (task) => set((state) => ({
    tasks: [...state.tasks, task]
  })),
  updateTask: (id, updates) => set((state) => ({
    tasks: state.tasks.map(task =>
      task.id === id ? { ...task, ...updates } : task
    )
  }))
}));`
    },
    githubUrl: 'https://github.com/example/task-manager',
    liveUrl: 'https://task-manager.example.com',
    createdAt: '2026-01-10',
    autoGenerated: false,
    highlights: ['Real-time', 'Offline Support', 'Full Stack'],
  },
  {
    id: 'p4',
    title: 'UI Component Library',
    description: 'A comprehensive React component library built with TypeScript and Storybook for rapid prototyping.',
    techStack: ['React', 'TypeScript', 'Storybook', 'Material UI', 'Jest'],
    type: 'Tool',
    status: 'completed',
    keyPoints: [
      '50+ reusable components',
      'Full TypeScript support',
      'Comprehensive Storybook documentation',
      '100% test coverage',
    ],
    solution: `A production-ready component library with comprehensive documentation and testing.

Features:
- 50+ reusable components
- Full TypeScript support with proper type definitions
- Storybook for component documentation
- Jest + React Testing Library for testing`,
    codeExample: {
      language: 'typescript',
      code: `interface ButtonProps {
  variant?: 'primary' | 'secondary' | 'outline';
  size?: 'small' | 'medium' | 'large';
  children: React.ReactNode;
  onClick?: () => void;
}

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'medium',
  children,
  onClick
}) => {
  return (
    <button
      className={\`btn btn-\${variant} btn-\${size}\`}
      onClick={onClick}
    >
      {children}
    </button>
  );
};`
    },
    githubUrl: 'https://github.com/example/component-library',
    createdAt: '2026-01-08',
    autoGenerated: false,
    highlights: ['Components', 'Storybook', 'Testing'],
  },
  {
    id: 'p5',
    title: 'Code Formatter Tool',
    description: 'A browser-based code formatter supporting multiple languages with syntax highlighting.',
    techStack: ['React', 'TypeScript', 'Prettier', 'Monaco Editor'],
    type: 'Tool',
    status: 'completed',
    keyPoints: [
      'Multi-language support',
      'Real-time formatting',
      'Export to multiple formats',
      'Zero dependencies',
    ],
    solution: `Browser-based code formatter with Monaco Editor integration.

Features:
- Support for multiple programming languages
- Real-time code formatting
- Export formatted code in various formats
- Monaco Editor for VS Code-like editing experience`,
    codeExample: {
      language: 'typescript',
      code: `import { Editor } from '@monaco-editor/react';
import prettier from 'prettier';

function CodeFormatter() {
  const [code, setCode] = useState('');
  const [language, setLanguage] = useState('typescript');

  const formatCode = async () => {
    const formatted = await prettier.format(code, {
      parser: language,
      plugins: [require('prettier/parser-typescript')],
    });
    setCode(formatted);
  };

  return (
    <Editor
      height="400px"
      language={language}
      value={code}
      onChange={(value) => setCode(value || '')}
    />
  );
}`
    },
    demoUrl: '/demos/code-formatter',
    createdAt: '2026-01-05',
    autoGenerated: false,
    highlights: ['Monaco Editor', 'Multi-language', 'Formatting'],
  },
  {
    id: 'p6',
    title: 'WebGL Visualization',
    description: 'Experimental 3D visualization using WebGL and Three.js for interactive data representation.',
    techStack: ['React', 'TypeScript', 'Three.js', 'WebGL', 'GLSL'],
    type: 'Experiment',
    status: 'in-progress',
    keyPoints: [
      'Real-time 3D rendering',
      'Custom shaders',
      'Interactive controls',
      'Performance optimized',
    ],
    solution: `Experimental WebGL visualization project using Three.js.

Features:
- Real-time 3D rendering with WebGL
- Custom GLSL shaders for advanced effects
- Interactive camera controls
- Performance optimizations for smooth rendering`,
    codeExample: {
      language: 'typescript',
      code: `import * as THREE from 'three';
import { useEffect, useRef } from 'react';

function WebGLVisualization() {
  const mountRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(75, 1, 0.1, 1000);
    const renderer = new THREE.WebGLRenderer({ antialias: true });

    renderer.setSize(800, 600);
    mountRef.current?.appendChild(renderer.domElement);

    const geometry = new THREE.BoxGeometry();
    const material = new THREE.MeshBasicMaterial({ color: 0x00ff00 });
    const cube = new THREE.Mesh(geometry, material);
    scene.add(cube);

    camera.position.z = 5;

    const animate = () => {
      requestAnimationFrame(animate);
      cube.rotation.x += 0.01;
      cube.rotation.y += 0.01;
      renderer.render(scene, camera);
    };
    animate();
  }, []);

  return <div ref={mountRef} />;
}`
    },
    demoUrl: '/demos/webgl',
    createdAt: '2026-01-03',
    autoGenerated: false,
    highlights: ['WebGL', 'Three.js', '3D Rendering'],
  },
]

export const projectTypes: ProjectType[] = ['Tool', 'Experiment', 'FullStack']

export const allTechStack = Array.from(new Set(projects.flatMap(p => p.techStack))).sort()
